name: time_trace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  path: ^1.9.1
  path_provider: ^2.1.5
  csv: ^6.0.0
  share_plus: ^7.2.1
  file_picker: ^10.3.8
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  
  google_nav_bar: ^5.0.7
  flutter_colorpicker: ^1.1.0
  # lottie: ^3.3.1
  # animations: ^2.0.11
  # fluttertoast: ^9.0.0
  flutter_slidable: ^4.0.3
  # home_widget: ^0.8.1
  fl_chart: ^1.1.1

  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  provider: ^6.1.5+1
  go_router: ^16.2.4
  equatable: ^2.0.7

  ## Debugging & Error Tracking
  # wiredash: ^2.4.0
  # dartz: ^0.10.1
  # bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  drift_dev: ^2.30.0
  build_runner: ^2.10.4

  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/app-icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
